export const BlogApi = [

    {title : "Health and Wellness- Ambhos", image: "/images/BlogImages/blog1.jpg", link:"https://ambhos.blogspot.com/2021/01/health-wellness.html", date: "17-Jan-2021", description: "A feeling, an experience of bad health is termed as illness. This illness can be physical or psychological. As per the recent scenario, the health-related issues have gradually increased, be it physical or psychological health issues."}
    ,{title: "AMLA- Phyllanthus Emblica- Ambhos", image:"/images/BlogImages/blog2.jpg", link:"https://ambhos.blogspot.com/2021/02/amla-phyllanthus-emblica.html", date:"13-Feb-2021", description:"Amla is the most important fruit according to Hindu Mythology. Its scientific name is Phyllanthus Emblica. Leigh Hunt rightly said, “The groundwork of all happiness is health”. The Indian gooseberry is rich in antioxidants, vitamin E, iron, calcium & has eight times more vitamin C than oranges.  Here are some facts which make Amla a superfood-"}
    ,{title: "Ginger-Ambhos ", image:"/images/BlogImages/blog3.jpg", link:"https://ambhos.blogspot.com/2021/02/ginger.html", date:"16-Feb-2021", description:"Ginger is an indispensable ingredient of Daadi maa ka khazaana from her kitchen. Ginger is a herbaceous perennial extensively known for its medicinal qualities. It has anti-bacterial, anti-viral and anti-inflammatory effects."}
    ,{title: "Turmeric - Ambhos ", image:"/images/BlogImages/blog4.jpg", link:"https://ambhos.blogspot.com/2021/02/turmeric.html", date:"16-Feb-2021", description:"Turmeric is a spice obtained from the plant. It can be regarded as a universal ingredient. Its stem is also used alternative medicine, also regarded as a natural aspirin."}
    ,{title: "Tulsi - Ambhos ", image:"/images/BlogImages/blog5.jpg", link:"https://ambhos.blogspot.com/2021/02/tulshi.html", date:"17-Feb-2021", description:"A Tulsi Article in Hindi -  Tulsi leaves are also referred to as Basil by Indians. Tulsi is considered the queen of all herbs in India. This herb can be found in the home of almost every Hindu and is considered sacred. Tulsi has its medicinal benefits."}
    ,{title: "Aerobics - Ambhos ", image:"/images/BlogImages/blog6.jpg", link:"https://ambhos.blogspot.com/2021/03/aerobics.html", date:"03-March-2021", description:"Lockdown, WFH, online classes left you lethargic, lackadaisical, grumpy, and unfit?! Aerobics can help you!! Now, what is aerobics? Aerobics is an exercising method that makes you sweat a lot along with a high breathing rate. It is a cardio work-out focussing on all aspects of well-being. It increases the strength, stamina, and flexibility of the body."}
    ,{title: "Cardio - Ambhos ", image:"/images/BlogImages/blog7.jpg", link:"https://ambhos.blogspot.com/2021/03/cardio.html", date:"16-Mar-2021", description:"How can I lose weight? Well this is the most frequent question asked by everyone, be it any generation. CARDIO is aerobic exercises which strengthens our heart and lungs.Cardio is a very effective way for adults to lose and maintain weight. It not only helps in losing weight but also keeps a check on serious health problems"}
    ,{title: "Cucumber (Cucumis Sativus) - Ambhos ", image:"/images/BlogImages/blog8.jpg", link:"https://ambhos.blogspot.com/2021/04/cucumber-cucumis-sativus.html", date:"6-Apr-2021", description:"Cucumber (Cucumis sativus) or popularly known as kheera in Hindi is a juicy, thin-skinned, green coloured vegetable. It is a creeper believed to have originated in the Indian subcontinent. It initially had a wild growth which was later domesticated. Owing to its hydrating, soothing, anti-oxidant and hypoallergenic nature, it has been for centuries to prevent or cure different ailments."}
    ,{title: "GYM - Ambhos ", image:"/images/BlogImages/blog9.jpg", link:"https://ambhos.blogspot.com/2021/04/gym.html", date:"10-Apr-2021", description:"Everything in your life needs a lot of hard work, dedication and motivation but it needs much more when it is about going to GYM You see the magic of strength? ? When you hit the gym, the first few days are painful, with aches everywhere. Later, even as you are consistent, the same pain that you experienced in the beginning, transforms itself into strength."}
    ,{title: "Coconut oil - Ambhos ", image:"/images/BlogImages/blog10.jpg", link:"https://ambhos.blogspot.com/2021/05/coconut-oil.html", date:"9-May-2021", description:"Coconut oil originates from the fruit(nut) coconut palm. It is also called copra oil and It contains a high level of saturated fat and is used as food oil and also in industries. Coconut oil is solid at room temperature and melts when heated."}
    ,{title: "IMPACT OF First COVID-19 Wave in INDIA - Ambhos ", image:"/images/BlogImages/blog11.jpg", link:"https://ambhos.blogspot.com/2021/06/impact-of-covid-wave-1-in-india.html", date:"1-June-2021", description:"STAY HOME STAY SAFE* *2 GAJ DOORI MASK HAI ZAROORI; The coronavirus disease (COVID-19) pandemic, which originated in the city of Wuhan, China, has quickly spread worldwide and has given rise to a "}
]